# ---- SoC / CPU ----
TARGET_BOARD_PLATFORM := msm7x27a
TARGET_BOARD_PLATFORM_GPU := qcom-adreno200
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a
TARGET_CPU_VARIANT := cortex-a5
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_LOWMEM := true

TARGET_BOOTLOADER_BOARD_NAME := y210
BOARD_VENDOR := huawei

# ---- Kernel prebuilt + offsets del header ----
TARGET_PREBUILT_KERNEL := device/huawei/y210/kernel


BOARD_KERNEL_BASE := 0x00200000
BOARD_KERNEL_PAGESIZE := 4096
BOARD_RAMDISK_OFFSET := 0x01100000
BOARD_TAGS_OFFSET := 0x00000100
BOARD_KERNEL_CMDLINE := console=ttyDCC0 androidboot.hardware=huawei

# ---- Particiones MTD / YAFFS2 ----
TARGET_USERIMAGES_USE_EXT4 := false
TARGET_USERIMAGES_USE_UBIFS := false
BOARD_USE_MTDUTILS := true
BOARD_FLASH_BLOCK_SIZE := 262144                   # 0x40000 erasesize
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00500000   # 5 MiB

BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := yaffs2
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := yaffs2
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE   := yaffs2
BOARD_CUSTIMAGE_FILE_SYSTEM_TYPE    := yaffs2

BOARD_SYSTEMIMAGE_PARTITION_SIZE := 195035136   # mtd4 actual size
BOARD_CACHEIMAGE_PARTITION_SIZE  := 60817408    # mtd5 (59392*1024)
BOARD_USERDATAIMAGE_PARTITION_SIZE := 167772160 # mtd6 (163840*1024)
BOARD_CUSTIMAGE_PARTITION_SIZE     := 20971520  # mtd8 (20480*1024)

# Recovery
BOARD_HAS_NO_SELECT_BUTTON := true
TARGET_RECOVERY_FSTAB := device/huawei/y210/ramdisk/recovery/twrp.fstab
BOARD_USE_CUSTOM_RECOVERY_FONT			:= "<font_7x16.h>"
TW_SECONDARY_BRIGHTNESS_PATH := "/sys/class/leds/button-backlight/brightness"

ifeq ($(TARGET_BUILD_VARIANT), eng)
  BOARD_CUSTOM_BOOTIMG_MK := device/huawei/y210/customrecoveryimg.mk
endif

TW_CUSTOM_THEME := device/huawei/y210/theme
TW_ADDITIONAL_RES := bootable/recovery/gui/theme/common/portrait.xml
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
TARGET_RECOVERY_INITRC := device/huawei/y210/ramdisk/recovery/init.rc
TW_DEVICE_VERSION := 0.61
TW_NO_REBOOT_BOOTLOADER := true
TW_INCLUDE_CRYPTO := false
TW_EXCLUDE_SUPERSU := true
TW_NO_CPU_TEMP := true

BOARD_HAS_LARGE_FILESYSTEM := true

TW_USE_MODEL_HARDWARE_ID_FOR_DEVICE_ID := true
TWRP_INCLUDE_LOGCAT := true
TW_NO_EXFAT := true
